#!/usr/bin/env bash
# shellcheck disable=SC2016,SC2088
# Source-of-truth helper for the dotfiles migration (Phase 1).
# SC2016 / SC2088 are suppressed intentionally:
# the tilde paths and backtick spans are literal markdown labels, not paths.
#
# Read-only. Inspects duplicate / overlapping config sources between
# configs/, backup-sanitized/home/, and scripts/, then emits a draft
# matrix at repo-docs/archive/migration-source-of-truth.draft.md with TBD markers
# for any pair that needs a human decision.
#
# Does NOT move, copy, or delete any file.
#
# Usage:
#   bash scripts/check-source-of-truth.sh [--output PATH]
#
# Exit code: 0 on success, 1 on missing prerequisites.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

OUTPUT="repo-docs/archive/migration-source-of-truth.draft.md"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --output)
      OUTPUT="$2"
      shift 2
      ;;
    -h|--help)
      sed -n '2,16p' "$0"
      exit 0
      ;;
    *)
      printf '[check-source-of-truth] unknown arg: %s\n' "$1" >&2
      exit 1
      ;;
  esac
done

command -v diff >/dev/null 2>&1 || {
  printf '[check-source-of-truth] diff not on PATH\n' >&2
  exit 1
}

mkdir -p "$(dirname "$OUTPUT")"

now="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

compare_pair() {
  # Echoes one matrix row for a candidate pair.
  # $1 = target label, $2 = path A, $3 = path B
  local label="$1" a="$2" b="$3"
  local a_exists=0 b_exists=0
  [[ -f "$a" ]] && a_exists=1
  [[ -f "$b" ]] && b_exists=1

  if [[ $a_exists -eq 0 && $b_exists -eq 0 ]]; then
    printf '| %s | %s, %s | NEITHER EXISTS | drop from matrix |\n' \
      "$label" "$a" "$b"
    return
  fi
  if [[ $a_exists -eq 0 ]]; then
    printf '| %s | %s | %s (only source) | migrate as-is |\n' \
      "$label" "$b" "$b"
    return
  fi
  if [[ $b_exists -eq 0 ]]; then
    printf '| %s | %s | %s (only source) | migrate as-is |\n' \
      "$label" "$a" "$a"
    return
  fi

  if diff -q "$a" "$b" >/dev/null 2>&1; then
    printf '| %s | %s, %s | IDENTICAL | keep either, drop the other |\n' \
      "$label" "$a" "$b"
    return
  fi

  local a_size b_size
  a_size="$(wc -c <"$a" | tr -d ' ')"
  b_size="$(wc -c <"$b" | tr -d ' ')"

  local a_mtime b_mtime newer
  a_mtime="$(git log -1 --format='%ct' -- "$a" 2>/dev/null || echo 0)"
  b_mtime="$(git log -1 --format='%ct' -- "$b" 2>/dev/null || echo 0)"
  if [[ "$a_mtime" == "0" && "$b_mtime" == "0" ]]; then
    newer="no git history; check fs mtime"
  elif (( a_mtime > b_mtime )); then
    newer="git: $a newer"
  elif (( b_mtime > a_mtime )); then
    newer="git: $b newer"
  else
    newer="git: same commit"
  fi

  printf '| %s | %s (%s bytes), %s (%s bytes) | TBD | DIFFER — %s |\n' \
    "$label" "$a" "$a_size" "$b" "$b_size" "$newer"
}

inventory_listing() {
  # Lists every file under $1 if the directory exists.
  local dir="$1"
  [[ -d "$dir" ]] || return 0
  ( cd "$REPO_ROOT" && find "$dir" -type f -print | sort )
}

{
  printf '# Source-of-truth matrix (DRAFT)\n\n'
  printf '_Generated by `scripts/check-source-of-truth.sh` at %s._\n\n' "$now"
  printf 'This file is **draft only**. Review every TBD row, decide the\n'
  printf 'winning source, then save the reviewed copy as\n'
  printf '`repo-docs/migration-source-of-truth.md`. Phase 2 reads only the final\n'
  printf 'reviewed file. Do not delete or move anything based on this draft.\n\n'

  printf '## Duplicate / overlapping config pairs\n\n'
  printf '| Target | Candidate sources | Chosen | Diff signal |\n'
  printf '|--------|-------------------|--------|-------------|\n'

  compare_pair "~/.zshrc" \
    "configs/shell/.zshrc" \
    "backup-sanitized/home/.zshrc"

  compare_pair "~/.gitconfig" \
    "configs/shell/.gitconfig" \
    "backup-sanitized/home/.gitconfig"

  compare_pair "~/.config/starship/starship.toml" \
    "configs/shell/starship.toml" \
    "backup-sanitized/home/.config/starship/starship.toml"

  compare_pair "~/.config/ghostty/config (typo check)" \
    "configs/ghostty/config" \
    "configs/ghostty/config-ghostyy"

  compare_pair "~/.config/ghostty/config (sources)" \
    "configs/ghostty/config" \
    "backup-sanitized/home/.config/ghostty/config"

  compare_pair "~/.local/bin/git-branch-origin" \
    "home/dot_local/bin/executable_git-branch-origin" \
    "backup-sanitized/home/.local/bin/git-branch-origin"

  printf '\n## SSH-agent helper disposition (decide before Phase 2)\n\n'
  printf '| Path | Disposition (migrate / keep as bootstrap helper / drop) | Reason |\n'
  printf '|------|---------------------------------------------------------|--------|\n'
  printf '| `configs/shell/ssh-agent/ssh-agent.sh` | TBD | shell snippet |\n'
  printf '| `configs/shell/ssh-agent/ssh-agent.fish` | TBD | fish variant |\n'
  printf '| `configs/shell/ssh-agent/README.md` | TBD | doc |\n'
  printf '| `scripts/unix/ssh-agent-setup.sh` | TBD | bootstrap helper |\n\n'

  printf '## Files with no duplicates (migrate directly)\n\n'
  for f in \
    backup-sanitized/home/.zprofile \
    backup-sanitized/home/.bashrc \
    backup-sanitized/home/.config/atuin/config.toml \
    backup-sanitized/home/.config/btop/btop.conf \
    backup-sanitized/home/.config/mise/config.toml \
    configs/karabiner/karabiner.json \
    configs/vscode/keybindings.json \
    configs/vscode/user/settings.json \
    configs/vscode/user/settings.minimal.json
  do
    if [[ -f "$f" ]]; then
      printf -- '- `%s`\n' "$f"
    else
      printf -- '- `%s` (MISSING — verify before relying on it)\n' "$f"
    fi
  done

  printf '\n## Whole-tree migrations\n\n'
  for d in configs/nvim configs/vscode repo-docs/templates/vscode; do
    if [[ -d "$d" ]]; then
      printf -- '- `%s/` (%s files)\n' "$d" "$(find "$d" -type f | wc -l | tr -d ' ')"
    fi
  done

  printf '\n## Inventory dumps (for cross-check)\n\n'
  printf '### `configs/` tree\n\n```\n'
  inventory_listing configs
  printf '```\n\n'
  printf '### `backup-sanitized/` tree\n\n```\n'
  inventory_listing backup-sanitized
  printf '```\n'
} > "$OUTPUT"

printf '[check-source-of-truth] draft written: %s\n' "$OUTPUT"
printf '[check-source-of-truth] resolve TBD rows, then save as repo-docs/migration-source-of-truth.md\n'
