#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUT_MD="$ROOT_DIR/docs/ai/repo-required-tools.md"

tmp_tools="$(mktemp)"
tmp_tools_sorted="$(mktemp)"
trap 'rm -f "$tmp_tools" "$tmp_tools_sorted"' EXIT

extract_tools_from_script() {
    local script="$1"

    # command -v <tool>
    sed -nE "s/.*command -v[[:space:]]+['\"]?([a-zA-Z0-9_.-]+).*/\1/p" "$script" >>"$tmp_tools" || true

    # required=(tool1 tool2 ...)
    sed -nE "s/.*required=\(([^)]*)\).*/\1/p" "$script" \
        | tr ' ' '\n' \
        | sed -E 's/["'"'"']//g' \
        | sed '/^$/d' >>"$tmp_tools" || true

    # for bin in a b c; do
    sed -nE "s/.*for[[:space:]]+bin[[:space:]]+in[[:space:]]+([^;]+);.*/\1/p" "$script" \
        | tr ' ' '\n' \
        | sed -E 's/["'"'"']//g' \
        | sed '/^$/d' >>"$tmp_tools" || true
}

while IFS= read -r script; do
    extract_tools_from_script "$script"
done < <(git -C "$ROOT_DIR" ls-files '*.sh')

cat <<'EOF' >>"$tmp_tools"
bash
git
php
rg
repomix
scc
jq
EOF

sed -E '/^\$|^\{|^\}|^#|^if$|^then$|^fi$|^do$|^done$/d' "$tmp_tools" \
    | sed -E '/^(for|in|while|local|case|esac|return|exit|printf|echo)$/d' \
    | sed -E '/[^a-zA-Z0-9_.-]/d' \
    | sort -u >"$tmp_tools_sorted"

mkdir -p "$(dirname "$OUT_MD")"

{
    printf '# Repository Required Tools\n\n'
    printf 'Generated by `scripts/ai/repo-tool-inventory.sh` from tracked `*.sh` scripts and baseline workflow requirements.\n\n'
    printf '## Mandatory\n\n'
    printf -- '- `bash`\n- `git`\n- `php`\n- `rg`\n- `repomix`\n- `scc`\n- `jq`\n\n'
    printf '## Additional Referenced Tools (optional by workflow path)\n\n'
    while IFS= read -r tool; do
        case "$tool" in
        bash|git|php|rg|repomix|scc|jq)
            ;;
        *)
            printf -- '- `%s`\n' "$tool"
            ;;
        esac
    done <"$tmp_tools_sorted"

    printf '\n## Verification\n\n'
    printf 'Run:\n\n'
    printf '```bash\n'
    printf 'bash scripts/ai/repo-tool-inventory.sh\n'
    printf 'bash scripts/doctor.sh\n'
    printf 'php tools/ai/ai.php toolchain --with repomix,scc --check\n'
    printf '```\n'
} >"$OUT_MD"

printf 'Wrote %s\n' "$OUT_MD"
