#!/usr/bin/env bash
# shellcheck disable=SC2016
# Package-ownership helper for the dotfiles migration (Phase 3).
#
# Read-only. Extracts candidate tool names from repo-docs/install-dev-tools.sh,
# cross-references repo-docs/software-and-cli-tools.md, optionally probes
# nixpkgs/Homebrew availability when those tools are present, and writes
# a draft matrix at repo-docs/archive/migration-package-ownership.draft.md with TBD
# rows for human review. Never installs anything.
#
# Usage:
#   bash ops/generate-package-matrix.sh [--output PATH] [--no-probe]
#
# Exit codes:
#   0  draft written
#   1  required input missing

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

OUTPUT="repo-docs/archive/migration-package-ownership.draft.md"
PROBE=1
while [[ $# -gt 0 ]]; do
  case "$1" in
    --output)
      OUTPUT="$2"
      shift 2
      ;;
    --no-probe)
      PROBE=0
      shift
      ;;
    -h|--help)
      sed -n '2,16p' "$0"
      exit 0
      ;;
    *)
      printf '[generate-package-matrix] unknown arg: %s\n' "$1" >&2
      exit 1
      ;;
  esac
done

INSTALL_SCRIPT="repo-docs/install-dev-tools.sh"
DOCS_FILE="repo-docs/software-and-cli-tools.md"

if [[ ! -f "$INSTALL_SCRIPT" ]]; then
  printf '[generate-package-matrix] missing %s\n' "$INSTALL_SCRIPT" >&2
  exit 1
fi

mkdir -p "$(dirname "$OUTPUT")"
now="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

# Extract candidate tool names from the FORMULAE=( ... ) and CASKS=( ... )
# blocks in repo-docs/install-dev-tools.sh. Handles both single-line forms
# (FOO=()) and multi-line forms (FOO=( \n item \n )). Awk-based to avoid
# sourcing the script.
extract_array() {
  local label="$1"
  awk -v label="$label" '
    # Single-line empty form: LABEL=()
    $0 ~ "^" label "=\\(\\)" { next }
    # Multi-line opener: LABEL=(
    $0 ~ "^" label "=\\($" { capture=1; next }
    capture && $0 ~ /^\)[[:space:]]*$/ { capture=0; next }
    capture {
      gsub(/[#].*/, "")
      gsub(/^[[:space:]]+|[[:space:]]+$/, "")
      if ($0 != "") print $0
    }
  ' "$INSTALL_SCRIPT"
}

formulae="$(extract_array FORMULAE | sort -u)"
casks="$(extract_array CASKS | sort -u)"

# Optional: tools mentioned in repo-docs/software-and-cli-tools.md but not in
# the install script. Surface via grep so the reviewer sees the gap.
extra_tools=""
if [[ -f "$DOCS_FILE" ]]; then
  # Tools that the docs explicitly mention but FORMULAE/CASKS omit.
  candidates="$(rg --no-line-number --only-matching \
    --regexp '\b(mkcert|stripe|copilot|colima|docker|p7zip|gh|gitleaks|tldr|tealdeer|files-to-prompt|code2prompt|scc|repomix|ast-grep)\b' \
    "$DOCS_FILE" | sort -u || true)"
  for c in $candidates; do
    if ! printf '%s\n' "$formulae" | grep -Fxq "$c"; then
      if ! printf '%s\n' "$casks" | grep -Fxq "$c"; then
        extra_tools="${extra_tools}${c}"$'\n'
      fi
    fi
  done
fi

probe_nix() {
  local pkg="$1"
  if [[ "$PROBE" -eq 0 ]]; then echo "(probe skipped)"; return; fi
  if ! command -v nix >/dev/null 2>&1; then echo "advisory only (no nix)"; return; fi
  if nix search --no-write-lock-file --json nixpkgs "^${pkg}$" 2>/dev/null \
       | grep -q "\"legacyPackages\\..*\\.${pkg}\""; then
    echo "found in nixpkgs"
  else
    echo "verify manually"
  fi
}

probe_cask() {
  local pkg="$1"
  if [[ "$PROBE" -eq 0 ]]; then echo "(probe skipped)"; return; fi
  if ! command -v brew >/dev/null 2>&1; then echo "advisory only (no brew)"; return; fi
  if brew info --cask "$pkg" >/dev/null 2>&1; then
    echo "valid cask"
  else
    echo "verify manually"
  fi
}

{
  printf '# Package ownership matrix (DRAFT)\n\n'
  printf '_Generated by `ops/generate-package-matrix.sh` at %s._\n\n' "$now"
  printf 'Owner column legend:\n'
  printf -- '- **Nix** — Home Manager `home.packages`\n'
  printf -- '- **nix-profile** — bootstrap-installed; not Home Manager\n'
  printf -- '- **mise** — runtime or per-project tool version\n'
  printf -- '- **cask** — Homebrew cask via nix-darwin (macOS only)\n'
  printf -- '- **manual** — out-of-band install\n'
  printf -- '- **DROPPED** — no longer used\n'
  printf -- '- **TBD** — owner not yet decided\n\n'
  printf 'Nix/Homebrew probes below are **advisory only**. Verify exact\n'
  printf 'attribute and cask names manually against\n'
  printf '<https://search.nixos.org/packages> and `brew search --casks <name>`\n'
  printf 'before Phase 6 writes any Nix code.\n\n'

  printf '## Formulae from %s\n\n' "$INSTALL_SCRIPT"
  printf '| Tool | Owner | Module / Manifest | Nix probe | Notes |\n'
  printf '|------|-------|-------------------|-----------|-------|\n'
  if [[ -z "$formulae" ]]; then
    printf '| _none extracted_ | — | — | — | inspect FORMULAE array |\n'
  else
    while IFS= read -r tool; do
      [[ -z "$tool" ]] && continue
      probe="$(probe_nix "$tool")"
      printf '| `%s` | TBD | TBD | %s | |\n' "$tool" "$probe"
    done <<< "$formulae"
  fi

  printf '\n## Casks from %s\n\n' "$INSTALL_SCRIPT"
  printf '| Cask | Owner | Module / Manifest | Cask probe | Notes |\n'
  printf '|------|-------|-------------------|------------|-------|\n'
  if [[ -z "$casks" ]]; then
    printf '| _no casks_ | n/a | n/a | n/a | install script has empty CASKS=() |\n'
  else
    while IFS= read -r cask; do
      [[ -z "$cask" ]] && continue
      probe="$(probe_cask "$cask")"
      printf '| `%s` | TBD | TBD | %s | |\n' "$cask" "$probe"
    done <<< "$casks"
  fi

  printf '\n## Tools mentioned in %s but missing from the install script\n\n' "$DOCS_FILE"
  if [[ -z "$extra_tools" ]]; then
    printf '_None detected._\n'
  else
    printf '| Tool | Owner | Module / Manifest | Notes |\n'
    printf '|------|-------|-------------------|-------|\n'
    while IFS= read -r extra; do
      [[ -z "$extra" ]] && continue
      printf '| `%s` | TBD | TBD | mentioned only in docs |\n' "$extra"
    done <<< "$extra_tools"
  fi

  printf '\n## Mandatory bootstrap-installed (via nix profile, not Home Manager)\n\n'
  printf '| Tool | Owner | Reason |\n'
  printf '|------|-------|--------|\n'
  printf '| `nix` | bootstrap | provided by Determinate installer |\n'
  printf '| `chezmoi` | nix-profile | chicken-and-egg: needed before Home Manager renders dotfiles |\n'
  printf '| `mise` | nix-profile | needed before mise tasks can run |\n'
  printf '| `home-manager` | nix-profile | needed to apply Home Manager configuration |\n'
  printf '| `lefthook` | nix-profile | needed to install git hooks |\n'

  printf '\n## Decisions still required\n\n'
  printf -- '- [ ] Resolve every TBD row above.\n'
  printf -- '- [ ] `direnv`: explicit retain or drop, with evidence that mise env activation covers current use.\n'
  printf -- '- [ ] PHP, Node, pnpm: confirm ownership is mise (not Nix) per architecture rules.\n'
  printf -- '- [ ] Any tool marked `verify manually`: confirm exact nixpkgs attribute or cask name.\n'
  printf -- '- [ ] macOS-only GUI apps: cask via nix-darwin Homebrew bridge; do not add to `home.packages`.\n'

  printf '\nAfter review, save the resolved matrix as `repo-docs/migration-package-ownership.md`.\n'
  printf 'Phase 6 reads only the reviewed file.\n'
} > "$OUTPUT"

printf '[generate-package-matrix] draft written: %s\n' "$OUTPUT"
printf '[generate-package-matrix] resolve TBD rows, then save as repo-docs/migration-package-ownership.md\n'
